### ISSUE TITLE
Add Markdown Visual Editor

### ISSUE THREAD

**Issue by julianfairfax** [kylejbrk/standard-notes-open-extended#14]
It would be nice if the new Markdown Visual editor could be added, or if you could tell me how I could use it on my free plan: https://github.com/standardnotes/app/tree/main/packages/components/dist/assets/org.standardnotes.markdown-visual-editor.

Markdown Visual (from the demo):
![Screenshot 2022-08-11 at 12-37-03 Demo Standard Notes End-To-End Encrypted Notes App](https://user-images.githubusercontent.com/43753131/184116568-d45ac44d-8ed5-402e-8c39-e49e14a8da39.png)

It would also be nice if the Midnight theme would work, since at the moment it seems the version you have doesn't on the current client.

**Comment by julianfairfax** [comment]
This isn't your project but I'm attempting to use https://github.com/iganeshk/standardnotes-extensions to achieve this and it's not working either. Any help in solving https://github.com/iganeshk/standardnotes-extensions/issues/45 would be appreciated. It seems you host this on GitHub Pages, so maybe you have some insight?

**Comment by kylejbrk** [comment]
Yea unfortunately all the changes SN made to their application broke a lot of stuff, and made this project not work as well.

I have a couple ideas to get all the extensions working again, including the new one you pointed out. Just a matter of finding the time to do it.

Also I am not familiar with gitlab or their version of pages. As for github pages, you need tom publish the source codes of the extensions as a github page. Then follow the SN publishing guide to add the extension to your account. Assuming you did all that, check the network log as you add the extension to see where the import may be going wrong. Could be a firewall issue or something.

**Comment by julianfairfax** [comment]
> Yea unfortunately all the changes SN made to their application broke a lot of stuff, and made this project not work as well.
> 
> I have a couple ideas to get all the extensions working again, including the new one you pointed out. Just a matter of finding the time to do it.
> 
> Also I am not familiar with gitlab or their version of pages. As for github pages, you need tom publish the source codes of the extensions as a github page. Then follow the SN publishing guide to add the extension to your account. Assuming you did all that, check the network log as you add the extension to see where the import may be going wrong. Could be a firewall issue or something.

I have done that: https://github.com/julianfairfax/standard-notes-extensions/tree/gh-pages. Turns out I forgot to deploy but that's fixed now. And I don't have a CNAME file, which seems to redirect every visit to julianfairfax.github.io/* to julianfairfax.githlab.io/*, even if the page is itself hosted on julianfairfax.github.io as well. However, neither the Visual Editor nor the Midnight theme work. Token Vault does, but it actually also works with the version I have hosted on GitLab Pages.

So it seems that a CNAME on GitHub Pages makes the whole GitHub Pages site inaccessible, even if content is hosted on it (doesn't just redirect what isn't), the Visual Editor and Midnight theme (at least) from https://github.com/iganeshk/standardnotes-extensions don't work, and hosting from GitLab Pages is the same as hosting from GitHub Pages (doesn't make anything additional work though).

**Comment by kylejbrk** [comment]
So im getting a little confused here. I think overall what you're going on github works fine.

The new markdown editor I cant speak to as I havent messed with it. However if you used with my code or the other project you posted, we were relying on the old way SN published their extension code. So as you pointed out Token Vault works fine, whereas some other apps, for example the Simple Task editor is broken because of the url in your JSON:

Current url in your index.json: https://julianfairfax.github.io/standard-notes-extensions/simple-task-editor/1.3.10/dist/index.html

URL it needs to be to work: https://julianfairfax.github.io/standard-notes-extensions/simple-task-editor/1.3.10/app/stylesheets/main.scss

A lot of paths and stuff got changed and need to be updated. But even worse the newest version of the code is longer hosted in the repos were pointing to.

**Comment by julianfairfax** [comment]
> So im getting a little confused here. I think overall what you're doing on github works fine.
> 
> The new markdown editor I cant speak to as I havent messed with it. However if you used with my code or the other project you posted, we were relying on the old way SN published their extension code. So as you pointed out Token Vault works fine, whereas some other apps, for example the Simple Task editor is broken because of the new way SN is developing their extensions. Look at the url for the Simple Task Editor in your index.json. That file no longer exists. Same for the Midnight Editor.
> 
> A lot of paths and stuff got changed and need to be updated. But even worse the newest version of the code is longer hosted in the repos were pointing to.

Well I didn't create or not create any of those files. They're all from the build tool at https://github.com/iganeshk/standardnotes-extensions, so it seems they need to fix them

**Comment by kylejbrk** [comment]
Ok well that is not my project so I'm not gonna discuss that one any further.

However, you're original issue says to add Markdown Visual Editor, which is within the scope of this project. So I will keep this open for now.

**Comment by kylejbrk** [comment]
Markdown Visual Editor has been added as well as a few of the other new extensions

https://github.com/kylejbrk/standard-notes-open-extended/tree/gh-pages#readme
