### ISSUE TITLE
The code does not work anymore in latest Standard Notes.

### ISSUE THREAD

**Issue by i90faytn3** [kylejbrk/standard-notes-open-extended#2]

**Comment by i90faytn3** [comment]
What to change: https://gitcdn.xyz/cdn/{$USERNAME}/standard-notes-open-extended/gh-pages/index.json
instead of 
https://gitcdn.xyz/repo/{$USERNAME}/standard-notes-open-extended/gh-pages/index.json

**Comment by kylejbrk** [comment]
Will fix this. Do you know why or when this change happened?

**Comment by kylejbrk** [comment]
c3ace0491308cfab4f71cffe33981493b9cbad7a fixes the issue

**Comment by i90faytn3** [comment]
Thanks!
