### ISSUE TITLE
Plus Editor 404's

### ISSUE THREAD

**Issue by brimwats** [kylejbrk/standard-notes-open-extended#3]
Hello!

Using the plus editor (both your version and selfhosting it) I get a 404:

404
File not found
The site configured at this address does not contain the requested file.
If this is your site, make sure that the filename case matches the URL.
For root URLs (like http://example.com/) you must provide an index.html file.
Read the full documentation for more information about using GitHub Pages.

**Comment by kylejbrk** [comment]
0a8120d25ebfd557c4422ef9713dfa750ac92f53 should fix the issue

**Comment by brimwats** [comment]
confirmed, thank you
