### ISSUE TITLE
No Extensions?

### ISSUE THREAD

**Issue by guy-who-googles** [kylejbrk/standard-notes-open-extended#5]
Ooh, I like this idea. Maybe I'm misunderstanding something though. 

After getting stuck on the self-host instructions, I wanted to double check what the extension page output should be. I added the extension activation code from the README: `https://gitcdn.xyz/cdn/kylejbrk/standard-notes-open-extended/gh-pages/index.json`, but wasn't able to see any.

I was able to use `https://snext.netlify.app/index.json` from [this project](https://github.com/JokerQyou/snextensions). I thought this might be related to #1 , but I'm using the Standard Notes Linux AppImage. Thoughts?

**Comment by kylejbrk** [comment]
Interesting. I think I'm able to replicate the issue. 

When viewing the requests, it appears that the URL is being blocked when trying to add the repo:
![image](https://user-images.githubusercontent.com/35229089/113722362-58a39400-96be-11eb-8281-69b1f0f36653.png)

I tried a different URL, similar to as you mentioned and it worked fine. I'm wondering if the devs blacklisted the URL?

Would you mind looking at the requests and see if you get the same thing? This can be done in browser or using the developer tools on the desktop app.

**Comment by kylejbrk** [comment]
Actually, I think this may be related to this issue with the CDN: https://github.com/schme16/gitcdn.xyz/issues/75#issuecomment-807969842

**Comment by guy-who-googles** [comment]
![Standard Notes Extension-Github](https://user-images.githubusercontent.com/79425037/113767273-b85c6800-96db-11eb-8127-d93daa005203.png)
Sorry not super knowledgeable about web stuff so I couldn't figure out how to get the exact same view, but hopefully that clarifies. 
Since the error is cert related the linked issue seems like the most likely cause.

**Comment by kylejbrk** [comment]
Looks like its back up
