### ISSUE TITLE
Does not work on Android

### ISSUE THREAD

**Issue by kfjcb** [kylejbrk/standard-notes-open-extended#8]
Extended editors and themes do not work anymore on Android devices. it redirects to the url value for example if I open any of Simple Task Manager notes, it opens "https://kyleburke.net/standard-notes-open-extended/simple-task-editor/dist/index.html". It has been like this for about weeks.

Tested Standard Notes v3.6.7 downloaded from F-Droid.

**Comment by kylejbrk** [comment]
The example you posted works.

Could you please try re-adding the repo and reinstalling any of the extensions that are not working? You currently only activate on desktop using: https://kyleburke.net/standard-notes-open-extended/
